project:
  type: book
  output-dir: docs

book:
  title: "政治学入門"
  author: "土井翔平"
  date: today
  sidebar:
    title: "政治学入門"
    collapse-level: 2
  chapters:
    - index.qmd
    - part: "導入"
      chapters: 
        # - info.qmd
        - intro.qmd
    - part: "比較政治"
    - part: "国際関係"

bibliography: references.bib

format:
  html:
    theme:
      - materia
      - custom.scss
    include-in-header: font.html
    mainfont: Noto Sans JP
    link-external-icon: true
    link-external-newwindow: true
    code-line-numbers: true

lang: ja
