project:
  type: website
  output-dir: docs

execute: 
  cache: true
  echo: false
  warning: false

website:
  title: "政治学入門"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 0
    contents:
      - index.qmd
      - column.qmd

format:
  html:
    theme: lumen
    include-in-header:
      - analytics.html
    mainfont: Helvetica Neue, Arial, Hiragino Kaku Gothic ProN, Hiragino Sans, BIZ UDPGothic, Meiryo, sans-serif
    toc: true
    number-sections: true
    reference-location: margin
    # fig-cap-location: margin
    link-external-icon: true
    link-external-newwindow: true
    fig-format: png
    smooth-scroll: true

bibliography: references.bib
lang: ja
