project:
  type: book
  output-dir: docs

book:
  title: "政治学入門"
  author: "土井翔平"
  date: today
  sidebar:
    title: "政治学入門"
    collapse-level: 2
  chapters:
    - index.qmd
    - part: "導入"
      chapters: 
        # - info.qmd
        - intro.qmd
    - part: "比較政治"
      chapters: 
        - electoral_system.qmd
        - voting_behavior.qmd
        - party_election.qmd
        # - political_regime.qmd
    - part: "国際関係"
      chapters: 
        - international_society.qmd
        - international_security.qmd

bibliography: references.bib

format:
  html:
    theme:
      - materia
      - custom.scss
    include-in-header: font.html
    mainfont: Noto Sans JP
    link-external-icon: true
    link-external-newwindow: true
    code-line-numbers: true
  # pdf:
  #   pdf-engine: latexmk
  #   pdf-engine-opt: "-xelatex"
  #   latex-output-dir: pdf
  #   latex-auto-install: false
  #   documentclass: bxjsarticle
  #   classoption:
  #     - xelatex
  #     - ja=standard
  #   include-in-header: 
  #     text: |
  #       \renewcommand{\thefootnote}{\arabic{footnote}}
  #   mainfont: Noto Serif CJK JP
  #   mainfontoptions: 
  #     - BoldFont=Noto Sans CJK JP
  #   number-sections: true
  #   fig-pos: "htpb"
  #   fig-format: png
  #   linkcolor: NavyBlue
  #   citecolor: NavyBlue
  #   urlcolor: NavyBlue
  #   cite-method: natbib
  #   biblio-config: true
  #   biblio-style: jecon

lang: ja
