# はじめに {.unnumbered}

政治学入門のうち[土井翔平](https://shohei-doi.github.io/)が担当する講義の資料です。2024年度は以下のセクションを担当します。

- 第1回：ガイダンス
    - 政治学とはどのような学問なのか？
- 第2-5回：比較政治
    - 選挙のルール
    - 有権者から見た選挙
    - 議員・政党から見た選挙
- 第12-15回：国際関係
    - 民主主義と権威主義
    - 政府なき国際社会
    - 戦争と平和の原因
    - 国際政治経済における協調

## 成績評価 {.unnumbered}

土井の授業に関する成績は**小テスト**と**平常点**をもとに評価します。

1. 平常点は授業に関する質問や発言が主です。
1. 小テストは1,2週間に1回を目安に行います。
    - Moodle上で行います。
    - 授業の内容に基づいて出題します。
        - 授業を真面目に聞き、ノートを取っていれば回答できる（受講せずに講義資料だけを見ても回答できない）難易度を目指します。
    - 具体的な出題範囲や回答期間などは授業中に改めてお知らせします。
        - 原則として、翌週の月曜日から木曜日の10時半（次回授業開始時）までを回答期間とします。

## 連絡 {.unnumbered}

土井の授業に関して質問したいときは授業中や授業後に直接話してください。授業時間外はメール、質問箱、Twitter（現X）のDMもしくはメンションで受け付けています。

- これらは平常点として加点するので、質問する際は名乗ってください。質問箱やTwitterで匿名で質問する場合は何かしらの形で土井に氏名あるいは学生番号を伝えてください。発言者が分からない場合は加点できません。
- 土井の研究室は法学部棟609号室です。アポイントメント無しで訪問しても構いません（その時に研究室にいてお相手する時間があるかは分かりませんが）。

## 参考書（国際関係）

特定の教科書を用いないが、自習のためにいくつかの参考書を紹介する。**国際関係論のテキストは多種多様なので、ぜひ読み比べて欲しい。**

- なにから読めばよいか分からない初学者の方は、まず @sunahara2020 や @sakamoto2020 など政治学の入門レベルの教科書の中の国際関係に関する箇所を読むことを勧める。その後、 @murata2023 など国際関係論の入門レベルの教科書を読むとよい。
- 身近な日本の話題から国際関係や国際法へ入門するものとして @sato2018 や @morikawa2016 などがある。
- 既に国際関係論を学んだことがある人は @nakanishi2013 や @yamakage2012 など が発展レベルの教科書としてある。また、発展レベルの政治学を扱う @kume2011 の国際関係に関する箇所も読むとよい。
- 国際関係の重要な知識をまとめたものとして @tanaka2010 は辞書的に使うことができる^[ただし、やや古いので注意。]。
- 国際関係論を本格的に学習したい人は英語のテキストとして @frieden2019 などに挑戦することを勧める。

国際関係論を直接扱うものではないが、この授業を理解する上で重要な周辺知識に関する参考書も挙げておく。

- 国際関係を理解する上で国際政治史、国際法、比較政治の知識は不可欠である。これらについても多くのテキストがあるが、入り口としてそれぞれ @ogawa2018 、@tamada2022 、 @kubo2016 を紹介する。
- 国際関係の一つの見方としてゲーム理論^[ゲーム理論自体はミクロ経済学の一分野である。]がある。ゲーム理論を用いた政治学の入門レベルの教科書として @asako2018 がある。また、 @okada2020 はゲーム理論を用いた国際関係論のテキストである（ただし、やや難易度は高い）。
- 国際関係をはじめ、様々な社会現象に関して原因と結果を検証する方法として統計的因果推論がある。入門レベルの教科書として @nakamuro2017, @ito2017, @matsubayashi2021 などがある。事例分析の方法としては @kume2013, @ito2022 などが参考になる。

:::{.callout-warning}
## 引用方法

技術的な問題から、講義ノートにおける引用方法は適切ではないので、レポート執筆などにおいて**参考にしないこと**。学生便覧の「引用の仕方」などを参照すること。
:::
