# 政治（学）って？ {.unnumbered}

:::{.callout-note}
## 政治学との悲哀

- Aさん「何学部なんですか？」
- ぼく「法学部なんです」
- Aさん「工学部なんですね」
- ぼく「いえ、法律の法学部です」
- Aさん「そうでしたか。弁護士になるんですね」
- ぼく「あ、法学部なんですけど政治学を勉強しています」
- Aさん「なるほど、政治家を目指しているんですね」
- ぼく「えっと、政治家になるつもりはなくて……」
- Aさん「（なんやこいつ……とりあえず話繋げなきゃ）本当に裏金ってあったんですかね？」
- ぼく「ニュースくらいのことしか知らなくて……」
- Aさん「そ、そうなんですね（もういいや）」
:::

## 政治学

政治学とはどのようなことをする学問だと思いますか？

- 政治家になるための学問？
- 政治談義？
- 政治学の教科書の目次
    - 砂原ほか「[政治学の第一歩](https://www.yuhikaku.co.jp/books/detail/9784641150782)」
    - 羅・前田「[権力を読み解く政治学](https://www.yuhikaku.co.jp/books/detail/9784641200081)」
    - 街鳥・山岡「[政治学入門](https://ua-book.shop-pro.jp/?pid=167017681)」
    - 犬塚ほか「[政治学入門](https://www.yuhikaku.co.jp/books/detail/9784641151086)」
    - 田村ほか「[政治学](https://www.keisoshobo.co.jp/book/b497001.html)」
    - 新川ほか「[政治学](https://www.yuhikaku.co.jp/books/detail/9784641149229)」
    - 川出・谷口「[政治学](https://www.utp.or.jp/book/b606377.html)」
- [日本政治学会による専門分野の分類](https://www.jpsa-web.org/mypage/field/)

## 政治

政治と聞いてどのようなイメージがありますか？　どのような言葉が思い浮かびますか？

- 選挙？　国会？　いかがわしい？
- 政治はどこにあるのか？
- 「社会に対する諸価値の権威的配分」（イーストン）
- 権力など「かなりな程度を含む人間関係の持続的なパターン」（ダール）
    - 社会、人間関係の持続的パターン／個人、その場限りの関係
    - 権威的配分、権力（利害対立）／取引、一心同体
    - 「AがBに対し、Bがそうでなければしないであろう行動をさせたならば、AはBに対し権力を持っているといえる」（ダール）
- 土井の理解：異なる目的（利害関係）を持つ人々や集団同士が合意、秩序を作ろうとする営み（あるいはその失敗）

## 多様性のある学問

曖昧な現象／多様な手法$\leadsto$未熟？　包容力？

- この授業で扱えるのは「ごく一部」だけです。
- 興味を持った方も、持たなかった方も、ぜひ法学部（あるいは他の学部）の専門科目へ！
